export interface MenuItem {
    id: string;
    category: 'Pasta' | 'Pizza' | 'Dessert' | 'Coffee';
    name: string;
    description: string;
    price: number;
    imageId: string;
  }
  
  export const menuData: MenuItem[] = [
    {
      id: 'coffee1',
      category: 'Coffee',
      name: 'flat white',
      description: 'Espresso with microfoam (steamed milk with fine bubbles).',
      price: 113,
      imageId: 'flat-white-coffee',
    },
    {
      id: 'coffee2',
      category: 'Coffee',
      name: 'latte',
      description: 'Espresso and steamed milk, with a thin layer of foam.',
      price: 125,
      imageId: 'latte-art-cup',
    },
    {
      id: 'coffee3',
      category: 'Coffee',
      name: 'cappuccino',
      description: 'Espresso-based drink with steamed milk foam.',
      price: 125,
      imageId: 'cappuccino-cup',
    },
    {
      id: 'coffee4',
      category: 'Coffee',
      name: 'americano',
      description: 'Espresso shots diluted with hot water.',
      price: 94,
      imageId: 'americano-coffee',
    },
    {
      id: 'coffee5',
      category: 'Coffee',
      name: 'espresso',
      description: 'A full-flavored, concentrated shot of coffee.',
      price: 88,
      imageId: 'espresso-shot-dark',
    },
    {
      id: 'coffee6',
      category: 'Coffee',
      name: 'macchiato',
      description: 'Espresso with a small amount of foamed milk.',
      price: 100,
      imageId: 'macchiato-glass',
    },
    {
      id: 'coffee7',
      category: 'Coffee',
      name: 'mocha',
      description: 'A chocolate-flavoured variant of a caffè latte.',
      price: 138,
      imageId: 'mocha-coffee',
    },
    {
      id: 'coffee8',
      category: 'Coffee',
      name: 'flavored latte',
      description: 'A sweet latte with vanilla, caramel, or hazelnut.',
      price: 144,
      imageId: 'flavored-latte',
    },
    {
      id: 'coffee9',
      category: 'Coffee',
      name: 'iced latte',
      description: 'A refreshing beverage made with a shot of rich espresso, chilled milk, and served over ice.',
      price: 163,
      imageId: 'iced-latte',
    },
    {
      id: 'pasta1',
      category: 'Pasta',
      name: 'spaghetti carbonara',
      description: 'Spaghetti with pancetta, egg yolks, and Pecorino Romano cheese.',
      price: 600,
      imageId: 'pasta-carbonara-bowl',
    },
    {
      id: 'pasta2',
      category: 'Pasta',
      name: 'fettuccine alfredo',
      description: 'Wide pasta in a creamy Parmesan and butter sauce.',
      price: 550,
      imageId: 'fettuccine-alfredo',
    },
    {
      id: 'pasta3',
      category: 'Pasta',
      name: 'pesto penne',
      description: 'Penne in basil pesto with garlic, pine nuts, and Parmesan.',
      price: 525,
      imageId: 'pesto-penne',
    },
    {
      id: 'pasta4',
      category: 'Pasta',
      name: 'lasagna',
      description: 'Classic beef lasagna with béchamel.',
      price: 625,
      imageId: 'lasagna-casserole',
    },
    {
      id: 'pasta5',
      category: 'Pasta',
      name: 'ravioli',
      description: 'Spinach and ricotta ravioli with sage butter.',
      price: 575,
      imageId: 'ravioli-sage-butter',
    },
    {
      id: 'pizza1',
      category: 'Pizza',
      name: 'margherita',
      description: 'Light crust with San Marzano tomato, mozzarella, and basil.',
      price: 450,
      imageId: 'margherita-pizza-classic',
    },
    {
      id: 'pizza2',
      category: 'Pizza',
      name: 'spicy pepperoni',
      description: 'Spicy pepperoni with a hot honey drizzle on a classic base.',
      price: 525,
      imageId: 'spicy-pepperoni-pizza',
    },
    {
      id: 'pizza3',
      category: 'Pizza',
      name: 'mushroom & truffle',
      description: 'Wild mushrooms, mozzarella, and black truffle oil on a white base.',
      price: 575,
      imageId: 'mushroom-truffle-pizza',
    },
    {
        id: 'pizza4',
        category: 'Pizza',
        name: 'prosciutto & arugula',
        description: 'Prosciutto, arugula, and shaved Parmesan.',
        price: 600,
        imageId: 'prosciutto-arugula-pizza',
    },
    {
        id: 'pizza5',
        category: 'Pizza',
        name: 'quattro formaggi',
        description: 'A blend of four classic cheeses.',
        price: 550,
        imageId: 'quattro-formaggi-pizza',
    },
    {
      id: 'dessert1',
      category: 'Dessert',
      name: 'tiramisu',
      description: 'Coffee-soaked ladyfingers with mascarpone cream and cocoa.',
      price: 300,
      imageId: 'classic-tiramisu',
    },
    {
      id: 'dessert2',
      category: 'Dessert',
      name: 'chocolate lava cake',
      description: 'Warm chocolate cake with a molten center and vanilla ice cream.',
      price: 325,
      imageId: 'chocolate-lava-cake',
    },
    {
      id: 'dessert3',
      category: 'Dessert',
      name: 'panna cotta',
      description: 'Silky, sweetened cream with a fresh seasonal berry coulis.',
      price: 275,
      imageId: 'panna-cotta-dessert',
    },
    {
        id: 'dessert4',
        category: 'Dessert',
        name: 'cheesecake',
        description: 'New York style cheesecake with berry compote.',
        price: 300,
        imageId: 'cheesecake-berry',
    },
    {
        id: 'dessert5',
        category: 'Dessert',
        name: 'cannoli',
        description: 'Crispy pastry shell with sweet ricotta.',
        price: 250,
        imageId: 'cannoli-dessert',
    },
    {
      id: 'coffee10',
      category: 'Coffee',
      name: 'cold brew',
      description: 'Smooth, low-acid coffee steeped overnight.',
      price: 138,
      imageId: 'cold-brew-coffee',
    },
    {
      id: 'pasta6',
      category: 'Pasta',
      name: 'spaghetti aglio e olio',
      description: 'Simple pasta with garlic, olive oil, and chili flakes.',
      price: 475,
      imageId: 'aglio-e-olio-pasta',
    },
    {
      id: 'pizza6',
      category: 'Pizza',
      name: 'hawaiian',
      description: 'A classic with ham and pineapple.',
      price: 500,
      imageId: 'hawaiian-pizza',
    },
    {
      id: 'dessert6',
      category: 'Dessert',
      name: 'affogato',
      description: 'Vanilla ice cream drowned in a shot of hot espresso.',
      price: 200,
      imageId: 'affogato-dessert',
    }
  ];
